import { logger as console } from '../shared/logger';
import { ExternalRequest } from '../types/external';
import { ExtensionResponseMessage } from '../types/extension';

/**
 * The native host name is part of the local installation contract. The host
 * manifest is generated by bridge/tm_bridge.py for the actual extension
 * id, so no extension id is embedded here.
 */
export const NATIVE_HOST_NAME = 'com.ctyx.tampermonkey_bridge';

export type NativeBridgeState = 'unavailable' | 'connecting' | 'connected' | 'error';

type NativeHello = {
    type: 'hello';
    protocol: 1;
    extensionId: string;
    extensionVersion: string;
};

type NativeReady = {
    type: 'ready';
    protocol: 1;
    bridgeVersion: string;
};

type NativeRequest = {
    type: 'request';
    id: string;
    request: ExternalRequest;
};

type NativeMessage = NativeReady | NativeRequest | { type: 'error'; message: string };

type NativeRequestHandler = (
    request: ExternalRequest,
    sendResponse: (response: ExtensionResponseMessage) => void
) => Promise<void>;

const MAX_RECONNECT_ATTEMPTS = 3;
const RECONNECT_DELAYS_MS = [ 1000, 5000, 30000 ];

let state: NativeBridgeState = 'unavailable';
let port: chrome.runtime.Port | undefined;
let reconnectTimer: ReturnType<typeof setTimeout> | undefined;
let reconnectAttempts = 0;
let started = false;
let requestHandler: NativeRequestHandler | undefined;

const setState = (next: NativeBridgeState) => {
    if (state !== next) console.info(`Native bridge: ${state} -> ${next}`);
    state = next;
};

const scheduleReconnect = () => {
    if (reconnectAttempts >= MAX_RECONNECT_ATTEMPTS || reconnectTimer !== undefined) return;

    const delay = RECONNECT_DELAYS_MS[reconnectAttempts] ?? RECONNECT_DELAYS_MS[RECONNECT_DELAYS_MS.length - 1];
    reconnectAttempts += 1;
    reconnectTimer = setTimeout(() => {
        reconnectTimer = undefined;
        connect();
    }, delay);
};

const handleMessage = (message: NativeMessage) => {
    if (message.type === 'ready') {
        reconnectAttempts = 0;
        setState('connected');
        return;
    }

    if (message.type === 'error') {
        console.error('Native bridge error:', message.message);
        setState('error');
        return;
    }

    if (message.type !== 'request' || !requestHandler) return;

    void requestHandler(message.request, response => {
        try {
            port?.postMessage({ type: 'response', id: message.id, response });
        } catch (error) {
            console.error('Native bridge response failed:', error);
        }
    }).catch(error => {
        console.error('Native bridge request failed:', error);
        try {
            port?.postMessage({
                type: 'response',
                id: message.id,
                response: { error: { number: 500, message: String(error) } }
            });
        } catch (sendError) {
            console.error('Native bridge error response failed:', sendError);
        }
    });
};

const disconnect = (disconnectedPort: chrome.runtime.Port) => {
    if (port !== disconnectedPort) return;
    port = undefined;
    void chrome.runtime.lastError;
    setState('error');
    scheduleReconnect();
};

function connect() {
    if (port || !requestHandler) return;

    try {
        setState('connecting');
        const nextPort = chrome.runtime.connectNative(NATIVE_HOST_NAME);
        port = nextPort;
        nextPort.onMessage.addListener((message: NativeMessage) => handleMessage(message));
        nextPort.onDisconnect.addListener(() => disconnect(nextPort));
        const manifest = chrome.runtime.getManifest();
        const hello: NativeHello = {
            type: 'hello',
            protocol: 1,
            extensionId: chrome.runtime.id,
            extensionVersion: manifest.version
        };
        nextPort.postMessage(hello);
    } catch (error) {
        port = undefined;
        console.warn('Native bridge is unavailable:', error);
        setState('unavailable');
        scheduleReconnect();
    }
}

export const startNativeBridge = (handler: NativeRequestHandler) => {
    if (started) return;
    started = true;
    requestHandler = handler;
    connect();
};

export const getNativeBridgeState = (): NativeBridgeState => state;
